/**
 * This file was automatically generated by the ICG based on the file:
 * /users/agirish/trick_tutorial/trick/trick_source/er7_utils/integration/symplectic_euler/include/symplectic_euler_second_order_ode_integrator.hh
 * This file contains database parameter declarations specific to the
 * data structures and enumerated types declared in the above file.
 * These database parameters are used by the Trick input and
 * data recording processors to gain access to important simulation
 * variable information.
 */

#define TRICK_IN_IOSRC
#include <stdlib.h>
#include "trick/MemoryManager.hh"
#include "trick/attributes.h"
#include "trick/parameter_types.h"
#include "trick/ClassSizeCheck.hh"
#include "trick/UnitsMap.hh"
#include "trick/checkpoint_stl.hh"
#include "/users/agirish/trick_tutorial/trick/trick_source/er7_utils/integration/symplectic_euler/include/symplectic_euler_second_order_ode_integrator.hh"

extern "C" {

ATTRIBUTES attrer7_utils__SymplecticEulerSecondOrderODEIntegrator[] = {
{"state_size", "int", "1", "", "",
  "n The sizes of the generalized position and generalized velocity vectors.",
  15,TRICK_INTEGER, sizeof(int), 0, 0, Language_CPP, 4,
  40, NULL, 1, {{2, 0}, {0, 0}, {0, 0}, {0, 0}, {0, 0}, {0, 0}, {0, 0}, {0, 0}},
  NULL, NULL, NULL, NULL},
{"problem_type", "er7_utils::Integration::ODEProblemType", "1", "", "",
  "n The type of problem to be solved.",
  15,TRICK_ENUMERATED, 0, 0, 0, Language_CPP, 4,
  48, NULL, 0, {{0, 0}, {0, 0}, {0, 0}, {0, 0}, {0, 0}, {0, 0}, {0, 0}, {0, 0}},
  NULL, NULL, NULL, NULL},
{"posdot", "double", "1", "", "",
  "n Position derivative.",
  15,TRICK_DOUBLE, sizeof(double), 0, 0, Language_CPP, 4,
  56, NULL, 1, {{0, 0}, {0, 0}, {0, 0}, {0, 0}, {0, 0}, {0, 0}, {0, 0}, {0, 0}},
  NULL, NULL, NULL, NULL},
{"", "", "1", "", "",
  "",
  15,TRICK_VOID, 0, 0, 0, Language_CPP, 0,
  0, NULL, 0, {{0, 0}, {0, 0}, {0, 0}, {0, 0}, {0, 0}, {0, 0}, {0, 0}, {0, 0}},
  NULL, NULL, NULL, NULL} };

} //extern "C"

namespace er7_utils {

void init_attrer7_utils__SymplecticEulerSecondOrderODEIntegrator() {

    static int initialized ;
    if (initialized) {
        return;
    }
    initialized = 1;

    trick_MM->add_attr_info(std::string(attrer7_utils__SymplecticEulerSecondOrderODEIntegrator[1].type_name) , &attrer7_utils__SymplecticEulerSecondOrderODEIntegrator[1], __FILE__ , __LINE__ ) ;

    ATTRIBUTES temp_attr ;

    trick_MM->add_attr_info( std::string("er7_utils::SecondOrderODEIntegrator"), &temp_attr , __FILE__ , __LINE__ ) ;
    trick_MM->add_attr_info( std::string("er7_utils::Er7UtilsDeletable"), &temp_attr , __FILE__ , __LINE__ ) ;
}
}

extern "C" {

void init_attrer7_utils__SymplecticEulerSecondOrderODEIntegrator_c_intf() {
    er7_utils::init_attrer7_utils__SymplecticEulerSecondOrderODEIntegrator() ;
}

size_t io_src_sizeof_er7_utils__SymplecticEulerSecondOrderODEIntegrator() {
    return sizeof(er7_utils::SymplecticEulerSecondOrderODEIntegrator) ;
}

void io_src_destruct_er7_utils__SymplecticEulerSecondOrderODEIntegrator(void* address __attribute__((unused)), int num __attribute__((unused))) {
    using namespace er7_utils;
    er7_utils::SymplecticEulerSecondOrderODEIntegrator* temp = (er7_utils::SymplecticEulerSecondOrderODEIntegrator*)address;
    for (int ii = 0; ii < num; ++ii) {
        temp[ii].~SymplecticEulerSecondOrderODEIntegrator();
    }
}

void io_src_delete_er7_utils__SymplecticEulerSecondOrderODEIntegrator(void* address) {
    delete (er7_utils::SymplecticEulerSecondOrderODEIntegrator*)address;
}

} //extern "C"

struct UnitsMaper7_utils__SymplecticEulerSecondOrderODEIntegrator {
    UnitsMaper7_utils__SymplecticEulerSecondOrderODEIntegrator() {
        Trick::UnitsMap* units_map_ptr = Trick::UnitsMap::units_map();
        units_map_ptr->add_param("SymplecticEulerSecondOrderODEIntegrator_state_size", "1") ;
        units_map_ptr->add_param("SymplecticEulerSecondOrderODEIntegrator_problem_type", "1") ;
        units_map_ptr->add_param("SymplecticEulerSecondOrderODEIntegrator_posdot", "1") ;
    }
} umer7_utils__SymplecticEulerSecondOrderODEIntegrator;

extern "C" {

ATTRIBUTES attrer7_utils__SymplecticEulerSimpleSecondOrderODEIntegrator[] = {
{"state_size", "int", "1", "", "",
  "n The sizes of the generalized position and generalized velocity vectors.",
  15,TRICK_INTEGER, sizeof(int), 0, 0, Language_CPP, 4,
  40, NULL, 1, {{2, 0}, {0, 0}, {0, 0}, {0, 0}, {0, 0}, {0, 0}, {0, 0}, {0, 0}},
  NULL, NULL, NULL, NULL},
{"problem_type", "er7_utils::Integration::ODEProblemType", "1", "", "",
  "n The type of problem to be solved.",
  15,TRICK_ENUMERATED, 0, 0, 0, Language_CPP, 4,
  48, NULL, 0, {{0, 0}, {0, 0}, {0, 0}, {0, 0}, {0, 0}, {0, 0}, {0, 0}, {0, 0}},
  NULL, NULL, NULL, NULL},
{"posdot", "double", "1", "", "",
  "n Position derivative.",
  15,TRICK_DOUBLE, sizeof(double), 0, 0, Language_CPP, 4,
  56, NULL, 1, {{0, 0}, {0, 0}, {0, 0}, {0, 0}, {0, 0}, {0, 0}, {0, 0}, {0, 0}},
  NULL, NULL, NULL, NULL},
{"", "", "1", "", "",
  "",
  15,TRICK_VOID, 0, 0, 0, Language_CPP, 0,
  0, NULL, 0, {{0, 0}, {0, 0}, {0, 0}, {0, 0}, {0, 0}, {0, 0}, {0, 0}, {0, 0}},
  NULL, NULL, NULL, NULL} };

} //extern "C"

namespace er7_utils {

void init_attrer7_utils__SymplecticEulerSimpleSecondOrderODEIntegrator() {

    static int initialized ;
    if (initialized) {
        return;
    }
    initialized = 1;

    trick_MM->add_attr_info(std::string(attrer7_utils__SymplecticEulerSimpleSecondOrderODEIntegrator[1].type_name) , &attrer7_utils__SymplecticEulerSimpleSecondOrderODEIntegrator[1], __FILE__ , __LINE__ ) ;

    ATTRIBUTES temp_attr ;

    trick_MM->add_attr_info( std::string("er7_utils::SymplecticEulerSecondOrderODEIntegrator"), &temp_attr , __FILE__ , __LINE__ ) ;
    trick_MM->add_attr_info( std::string("er7_utils::Er7UtilsDeletable"), &temp_attr , __FILE__ , __LINE__ ) ;
}
}

extern "C" {

void init_attrer7_utils__SymplecticEulerSimpleSecondOrderODEIntegrator_c_intf() {
    er7_utils::init_attrer7_utils__SymplecticEulerSimpleSecondOrderODEIntegrator() ;
}

size_t io_src_sizeof_er7_utils__SymplecticEulerSimpleSecondOrderODEIntegrator() {
    return sizeof(er7_utils::SymplecticEulerSimpleSecondOrderODEIntegrator) ;
}

void* io_src_allocate_er7_utils__SymplecticEulerSimpleSecondOrderODEIntegrator(int num) {
    er7_utils::SymplecticEulerSimpleSecondOrderODEIntegrator* temp = (er7_utils::SymplecticEulerSimpleSecondOrderODEIntegrator*)calloc(num, sizeof(er7_utils::SymplecticEulerSimpleSecondOrderODEIntegrator));
    for (int ii = 0; ii < num; ++ii) {
        new(&temp[ii]) er7_utils::SymplecticEulerSimpleSecondOrderODEIntegrator();
    }
    return (void*)temp;
}

void io_src_destruct_er7_utils__SymplecticEulerSimpleSecondOrderODEIntegrator(void* address __attribute__((unused)), int num __attribute__((unused))) {
    using namespace er7_utils;
    er7_utils::SymplecticEulerSimpleSecondOrderODEIntegrator* temp = (er7_utils::SymplecticEulerSimpleSecondOrderODEIntegrator*)address;
    for (int ii = 0; ii < num; ++ii) {
        temp[ii].~SymplecticEulerSimpleSecondOrderODEIntegrator();
    }
}

void io_src_delete_er7_utils__SymplecticEulerSimpleSecondOrderODEIntegrator(void* address) {
    delete (er7_utils::SymplecticEulerSimpleSecondOrderODEIntegrator*)address;
}

} //extern "C"

struct UnitsMaper7_utils__SymplecticEulerSimpleSecondOrderODEIntegrator {
    UnitsMaper7_utils__SymplecticEulerSimpleSecondOrderODEIntegrator() {
        Trick::UnitsMap* units_map_ptr = Trick::UnitsMap::units_map();
        units_map_ptr->add_param("SymplecticEulerSimpleSecondOrderODEIntegrator_state_size", "1") ;
        units_map_ptr->add_param("SymplecticEulerSimpleSecondOrderODEIntegrator_problem_type", "1") ;
        units_map_ptr->add_param("SymplecticEulerSimpleSecondOrderODEIntegrator_posdot", "1") ;
    }
} umer7_utils__SymplecticEulerSimpleSecondOrderODEIntegrator;

extern "C" {

ATTRIBUTES attrer7_utils__SymplecticEulerGeneralizedDerivSecondOrderODEIntegrator[] = {
{"state_size", "int", "1", "", "",
  "n The sizes of the generalized position and generalized velocity vectors.",
  15,TRICK_INTEGER, sizeof(int), 0, 0, Language_CPP, 4,
  40, NULL, 1, {{2, 0}, {0, 0}, {0, 0}, {0, 0}, {0, 0}, {0, 0}, {0, 0}, {0, 0}},
  NULL, NULL, NULL, NULL},
{"problem_type", "er7_utils::Integration::ODEProblemType", "1", "", "",
  "n The type of problem to be solved.",
  15,TRICK_ENUMERATED, 0, 0, 0, Language_CPP, 4,
  48, NULL, 0, {{0, 0}, {0, 0}, {0, 0}, {0, 0}, {0, 0}, {0, 0}, {0, 0}, {0, 0}},
  NULL, NULL, NULL, NULL},
{"posdot", "double", "1", "", "",
  "n Position derivative.",
  15,TRICK_DOUBLE, sizeof(double), 0, 0, Language_CPP, 4,
  56, NULL, 1, {{0, 0}, {0, 0}, {0, 0}, {0, 0}, {0, 0}, {0, 0}, {0, 0}, {0, 0}},
  NULL, NULL, NULL, NULL},
{"", "", "1", "", "",
  "",
  15,TRICK_VOID, 0, 0, 0, Language_CPP, 0,
  0, NULL, 0, {{0, 0}, {0, 0}, {0, 0}, {0, 0}, {0, 0}, {0, 0}, {0, 0}, {0, 0}},
  NULL, NULL, NULL, NULL} };

} //extern "C"

namespace er7_utils {

void init_attrer7_utils__SymplecticEulerGeneralizedDerivSecondOrderODEIntegrator() {

    static int initialized ;
    if (initialized) {
        return;
    }
    initialized = 1;

    trick_MM->add_attr_info(std::string(attrer7_utils__SymplecticEulerGeneralizedDerivSecondOrderODEIntegrator[1].type_name) , &attrer7_utils__SymplecticEulerGeneralizedDerivSecondOrderODEIntegrator[1], __FILE__ , __LINE__ ) ;

    ATTRIBUTES temp_attr ;

    trick_MM->add_attr_info( std::string("er7_utils::SymplecticEulerSecondOrderODEIntegrator"), &temp_attr , __FILE__ , __LINE__ ) ;
    trick_MM->add_attr_info( std::string("er7_utils::Er7UtilsDeletable"), &temp_attr , __FILE__ , __LINE__ ) ;
}
}

extern "C" {

void init_attrer7_utils__SymplecticEulerGeneralizedDerivSecondOrderODEIntegrator_c_intf() {
    er7_utils::init_attrer7_utils__SymplecticEulerGeneralizedDerivSecondOrderODEIntegrator() ;
}

size_t io_src_sizeof_er7_utils__SymplecticEulerGeneralizedDerivSecondOrderODEIntegrator() {
    return sizeof(er7_utils::SymplecticEulerGeneralizedDerivSecondOrderODEIntegrator) ;
}

void* io_src_allocate_er7_utils__SymplecticEulerGeneralizedDerivSecondOrderODEIntegrator(int num) {
    er7_utils::SymplecticEulerGeneralizedDerivSecondOrderODEIntegrator* temp = (er7_utils::SymplecticEulerGeneralizedDerivSecondOrderODEIntegrator*)calloc(num, sizeof(er7_utils::SymplecticEulerGeneralizedDerivSecondOrderODEIntegrator));
    for (int ii = 0; ii < num; ++ii) {
        new(&temp[ii]) er7_utils::SymplecticEulerGeneralizedDerivSecondOrderODEIntegrator();
    }
    return (void*)temp;
}

void io_src_destruct_er7_utils__SymplecticEulerGeneralizedDerivSecondOrderODEIntegrator(void* address __attribute__((unused)), int num __attribute__((unused))) {
    using namespace er7_utils;
    er7_utils::SymplecticEulerGeneralizedDerivSecondOrderODEIntegrator* temp = (er7_utils::SymplecticEulerGeneralizedDerivSecondOrderODEIntegrator*)address;
    for (int ii = 0; ii < num; ++ii) {
        temp[ii].~SymplecticEulerGeneralizedDerivSecondOrderODEIntegrator();
    }
}

void io_src_delete_er7_utils__SymplecticEulerGeneralizedDerivSecondOrderODEIntegrator(void* address) {
    delete (er7_utils::SymplecticEulerGeneralizedDerivSecondOrderODEIntegrator*)address;
}

} //extern "C"

struct UnitsMaper7_utils__SymplecticEulerGeneralizedDerivSecondOrderODEIntegrator {
    UnitsMaper7_utils__SymplecticEulerGeneralizedDerivSecondOrderODEIntegrator() {
        Trick::UnitsMap* units_map_ptr = Trick::UnitsMap::units_map();
        units_map_ptr->add_param("SymplecticEulerGeneralizedDerivSecondOrderODEIntegrator_state_size", "1") ;
        units_map_ptr->add_param("SymplecticEulerGeneralizedDerivSecondOrderODEIntegrator_problem_type", "1") ;
        units_map_ptr->add_param("SymplecticEulerGeneralizedDerivSecondOrderODEIntegrator_posdot", "1") ;
    }
} umer7_utils__SymplecticEulerGeneralizedDerivSecondOrderODEIntegrator;

extern "C" {

ATTRIBUTES attrer7_utils__SymplecticEulerGeneralizedStepSecondOrderODEIntegrator[] = {
{"state_size", "int", "1", "", "",
  "n The sizes of the generalized position and generalized velocity vectors.",
  15,TRICK_INTEGER, sizeof(int), 0, 0, Language_CPP, 4,
  40, NULL, 1, {{2, 0}, {0, 0}, {0, 0}, {0, 0}, {0, 0}, {0, 0}, {0, 0}, {0, 0}},
  NULL, NULL, NULL, NULL},
{"problem_type", "er7_utils::Integration::ODEProblemType", "1", "", "",
  "n The type of problem to be solved.",
  15,TRICK_ENUMERATED, 0, 0, 0, Language_CPP, 4,
  48, NULL, 0, {{0, 0}, {0, 0}, {0, 0}, {0, 0}, {0, 0}, {0, 0}, {0, 0}, {0, 0}},
  NULL, NULL, NULL, NULL},
{"posdot", "double", "1", "", "",
  "n Position derivative.",
  15,TRICK_DOUBLE, sizeof(double), 0, 0, Language_CPP, 4,
  56, NULL, 1, {{0, 0}, {0, 0}, {0, 0}, {0, 0}, {0, 0}, {0, 0}, {0, 0}, {0, 0}},
  NULL, NULL, NULL, NULL},
{"", "", "1", "", "",
  "",
  15,TRICK_VOID, 0, 0, 0, Language_CPP, 0,
  0, NULL, 0, {{0, 0}, {0, 0}, {0, 0}, {0, 0}, {0, 0}, {0, 0}, {0, 0}, {0, 0}},
  NULL, NULL, NULL, NULL} };

} //extern "C"

namespace er7_utils {

void init_attrer7_utils__SymplecticEulerGeneralizedStepSecondOrderODEIntegrator() {

    static int initialized ;
    if (initialized) {
        return;
    }
    initialized = 1;

    trick_MM->add_attr_info(std::string(attrer7_utils__SymplecticEulerGeneralizedStepSecondOrderODEIntegrator[1].type_name) , &attrer7_utils__SymplecticEulerGeneralizedStepSecondOrderODEIntegrator[1], __FILE__ , __LINE__ ) ;

    ATTRIBUTES temp_attr ;

    trick_MM->add_attr_info( std::string("er7_utils::SymplecticEulerSecondOrderODEIntegrator"), &temp_attr , __FILE__ , __LINE__ ) ;
    trick_MM->add_attr_info( std::string("er7_utils::Er7UtilsDeletable"), &temp_attr , __FILE__ , __LINE__ ) ;
}
}

extern "C" {

void init_attrer7_utils__SymplecticEulerGeneralizedStepSecondOrderODEIntegrator_c_intf() {
    er7_utils::init_attrer7_utils__SymplecticEulerGeneralizedStepSecondOrderODEIntegrator() ;
}

size_t io_src_sizeof_er7_utils__SymplecticEulerGeneralizedStepSecondOrderODEIntegrator() {
    return sizeof(er7_utils::SymplecticEulerGeneralizedStepSecondOrderODEIntegrator) ;
}

void* io_src_allocate_er7_utils__SymplecticEulerGeneralizedStepSecondOrderODEIntegrator(int num) {
    er7_utils::SymplecticEulerGeneralizedStepSecondOrderODEIntegrator* temp = (er7_utils::SymplecticEulerGeneralizedStepSecondOrderODEIntegrator*)calloc(num, sizeof(er7_utils::SymplecticEulerGeneralizedStepSecondOrderODEIntegrator));
    for (int ii = 0; ii < num; ++ii) {
        new(&temp[ii]) er7_utils::SymplecticEulerGeneralizedStepSecondOrderODEIntegrator();
    }
    return (void*)temp;
}

void io_src_destruct_er7_utils__SymplecticEulerGeneralizedStepSecondOrderODEIntegrator(void* address __attribute__((unused)), int num __attribute__((unused))) {
    using namespace er7_utils;
    er7_utils::SymplecticEulerGeneralizedStepSecondOrderODEIntegrator* temp = (er7_utils::SymplecticEulerGeneralizedStepSecondOrderODEIntegrator*)address;
    for (int ii = 0; ii < num; ++ii) {
        temp[ii].~SymplecticEulerGeneralizedStepSecondOrderODEIntegrator();
    }
}

void io_src_delete_er7_utils__SymplecticEulerGeneralizedStepSecondOrderODEIntegrator(void* address) {
    delete (er7_utils::SymplecticEulerGeneralizedStepSecondOrderODEIntegrator*)address;
}

} //extern "C"

struct UnitsMaper7_utils__SymplecticEulerGeneralizedStepSecondOrderODEIntegrator {
    UnitsMaper7_utils__SymplecticEulerGeneralizedStepSecondOrderODEIntegrator() {
        Trick::UnitsMap* units_map_ptr = Trick::UnitsMap::units_map();
        units_map_ptr->add_param("SymplecticEulerGeneralizedStepSecondOrderODEIntegrator_state_size", "1") ;
        units_map_ptr->add_param("SymplecticEulerGeneralizedStepSecondOrderODEIntegrator_problem_type", "1") ;
        units_map_ptr->add_param("SymplecticEulerGeneralizedStepSecondOrderODEIntegrator_posdot", "1") ;
    }
} umer7_utils__SymplecticEulerGeneralizedStepSecondOrderODEIntegrator;

