/**
 * This file was automatically generated by the ICG based on the file:
 * /users/agirish/trick_tutorial/trick/trick_source/er7_utils/integration/nl2/include/nl2_integrator_constructor.hh
 * This file contains database parameter declarations specific to the
 * data structures and enumerated types declared in the above file.
 * These database parameters are used by the Trick input and
 * data recording processors to gain access to important simulation
 * variable information.
 */

#define TRICK_IN_IOSRC
#include <stdlib.h>
#include "trick/MemoryManager.hh"
#include "trick/attributes.h"
#include "trick/parameter_types.h"
#include "trick/ClassSizeCheck.hh"
#include "trick/UnitsMap.hh"
#include "trick/checkpoint_stl.hh"
#include "/users/agirish/trick_tutorial/trick/trick_source/er7_utils/integration/nl2/include/nl2_integrator_constructor.hh"

extern "C" {

ATTRIBUTES attrer7_utils__NystromLear2IntegratorConstructor[] = {
{"", "", "1", "", "",
  "",
  15,TRICK_VOID, 0, 0, 0, Language_CPP, 0,
  0, NULL, 0, {{0, 0}, {0, 0}, {0, 0}, {0, 0}, {0, 0}, {0, 0}, {0, 0}, {0, 0}},
  NULL, NULL, NULL, NULL} };

} //extern "C"

namespace er7_utils {

void init_attrer7_utils__NystromLear2IntegratorConstructor() {

    static int initialized ;
    if (initialized) {
        return;
    }
    initialized = 1;


    ATTRIBUTES temp_attr ;

    trick_MM->add_attr_info( std::string("er7_utils::IntegratorConstructor"), &temp_attr , __FILE__ , __LINE__ ) ;
    trick_MM->add_attr_info( std::string("er7_utils::Er7UtilsDeletable"), &temp_attr , __FILE__ , __LINE__ ) ;
}
}

extern "C" {

void init_attrer7_utils__NystromLear2IntegratorConstructor_c_intf() {
    er7_utils::init_attrer7_utils__NystromLear2IntegratorConstructor() ;
}

size_t io_src_sizeof_er7_utils__NystromLear2IntegratorConstructor() {
    return sizeof(er7_utils::NystromLear2IntegratorConstructor) ;
}

void* io_src_allocate_er7_utils__NystromLear2IntegratorConstructor(int num) {
    er7_utils::NystromLear2IntegratorConstructor* temp = (er7_utils::NystromLear2IntegratorConstructor*)calloc(num, sizeof(er7_utils::NystromLear2IntegratorConstructor));
    for (int ii = 0; ii < num; ++ii) {
        new(&temp[ii]) er7_utils::NystromLear2IntegratorConstructor();
    }
    return (void*)temp;
}

void io_src_destruct_er7_utils__NystromLear2IntegratorConstructor(void* address __attribute__((unused)), int num __attribute__((unused))) {
    using namespace er7_utils;
    er7_utils::NystromLear2IntegratorConstructor* temp = (er7_utils::NystromLear2IntegratorConstructor*)address;
    for (int ii = 0; ii < num; ++ii) {
        temp[ii].~NystromLear2IntegratorConstructor();
    }
}

void io_src_delete_er7_utils__NystromLear2IntegratorConstructor(void* address) {
    delete (er7_utils::NystromLear2IntegratorConstructor*)address;
}

} //extern "C"

struct UnitsMaper7_utils__NystromLear2IntegratorConstructor {
} umer7_utils__NystromLear2IntegratorConstructor;

