/**
 * This file was automatically generated by the ICG based on the file:
 * /users/agirish/trick_tutorial/trick/trick_source/er7_utils/trick/integration/include/trick_second_order_ode_integrator.hh
 * This file contains database parameter declarations specific to the
 * data structures and enumerated types declared in the above file.
 * These database parameters are used by the Trick input and
 * data recording processors to gain access to important simulation
 * variable information.
 */

#define TRICK_IN_IOSRC
#include <stdlib.h>
#include "trick/MemoryManager.hh"
#include "trick/attributes.h"
#include "trick/parameter_types.h"
#include "trick/ClassSizeCheck.hh"
#include "trick/UnitsMap.hh"
#include "trick/checkpoint_stl.hh"
#include "/users/agirish/trick_tutorial/trick/trick_source/er7_utils/trick/integration/include/trick_second_order_ode_integrator.hh"

extern "C" {

ATTRIBUTES attrer7_utils__TrickSecondOrderOdeIntegrator[] = {
{"num_state", "int", "1", "", "",
  "",
  15,TRICK_INTEGER, sizeof(int), 0, 0, Language_CPP, 0,
  8, NULL, 0, {{0, 0}, {0, 0}, {0, 0}, {0, 0}, {0, 0}, {0, 0}, {0, 0}, {0, 0}},
  NULL, NULL, NULL, NULL},
{"intermediate_step", "int", "1", "", "",
  "",
  15,TRICK_INTEGER, sizeof(int), 0, 0, Language_CPP, 0,
  12, NULL, 0, {{0, 0}, {0, 0}, {0, 0}, {0, 0}, {0, 0}, {0, 0}, {0, 0}, {0, 0}},
  NULL, NULL, NULL, NULL},
{"first_step_deriv", "bool", "1", "", "",
  "",
  15,TRICK_BOOLEAN, sizeof(bool), 0, 0, Language_CPP, 0,
  16, NULL, 0, {{0, 0}, {0, 0}, {0, 0}, {0, 0}, {0, 0}, {0, 0}, {0, 0}, {0, 0}},
  NULL, NULL, NULL, NULL},
{"last_step_deriv", "bool", "1", "", "",
  "",
  15,TRICK_BOOLEAN, sizeof(bool), 0, 0, Language_CPP, 0,
  17, NULL, 0, {{0, 0}, {0, 0}, {0, 0}, {0, 0}, {0, 0}, {0, 0}, {0, 0}, {0, 0}},
  NULL, NULL, NULL, NULL},
{"is_2nd_order_ODE_technique", "bool", "1", "", "",
  "",
  15,TRICK_BOOLEAN, sizeof(bool), 0, 0, Language_CPP, 4,
  18, NULL, 0, {{0, 0}, {0, 0}, {0, 0}, {0, 0}, {0, 0}, {0, 0}, {0, 0}, {0, 0}},
  NULL, NULL, NULL, NULL},
{"use_deriv2", "bool", "1", "", "",
  "",
  15,TRICK_BOOLEAN, sizeof(bool), 0, 0, Language_CPP, 4,
  19, NULL, 0, {{0, 0}, {0, 0}, {0, 0}, {0, 0}, {0, 0}, {0, 0}, {0, 0}, {0, 0}},
  NULL, NULL, NULL, NULL},
{"dt", "double", "1", "", "",
  "",
  15,TRICK_DOUBLE, sizeof(double), 0, 0, Language_CPP, 4,
  24, NULL, 0, {{0, 0}, {0, 0}, {0, 0}, {0, 0}, {0, 0}, {0, 0}, {0, 0}, {0, 0}},
  NULL, NULL, NULL, NULL},
{"target_integ_time", "double", "1", "", "",
  "",
  15,TRICK_DOUBLE, sizeof(double), 0, 0, Language_CPP, 4,
  32, NULL, 0, {{0, 0}, {0, 0}, {0, 0}, {0, 0}, {0, 0}, {0, 0}, {0, 0}, {0, 0}},
  NULL, NULL, NULL, NULL},
{"state", "double", "1", "", "",
  "",
  15,TRICK_DOUBLE, sizeof(double), 0, 0, Language_CPP, 0,
  40, NULL, 1, {{0, 0}, {0, 0}, {0, 0}, {0, 0}, {0, 0}, {0, 0}, {0, 0}, {0, 0}},
  NULL, NULL, NULL, NULL},
{"deriv", "double", "1", "", "",
  "",
  15,TRICK_DOUBLE, sizeof(double), 0, 0, Language_CPP, 0,
  48, NULL, 2, {{0, 0}, {0, 0}, {0, 0}, {0, 0}, {0, 0}, {0, 0}, {0, 0}, {0, 0}},
  NULL, NULL, NULL, NULL},
{"deriv2", "double", "1", "", "",
  "",
  15,TRICK_DOUBLE, sizeof(double), 0, 0, Language_CPP, 0,
  56, NULL, 2, {{0, 0}, {0, 0}, {0, 0}, {0, 0}, {0, 0}, {0, 0}, {0, 0}, {0, 0}},
  NULL, NULL, NULL, NULL},
{"state_ws", "double", "1", "", "",
  "",
  15,TRICK_DOUBLE, sizeof(double), 0, 0, Language_CPP, 0,
  64, NULL, 2, {{0, 0}, {0, 0}, {0, 0}, {0, 0}, {0, 0}, {0, 0}, {0, 0}, {0, 0}},
  NULL, NULL, NULL, NULL},
{"time", "double", "1", "", "",
  "",
  15,TRICK_DOUBLE, sizeof(double), 0, 0, Language_CPP, 0,
  72, NULL, 0, {{0, 0}, {0, 0}, {0, 0}, {0, 0}, {0, 0}, {0, 0}, {0, 0}, {0, 0}},
  NULL, NULL, NULL, NULL},
{"time_0", "double", "1", "", "",
  "",
  15,TRICK_DOUBLE, sizeof(double), 0, 0, Language_CPP, 0,
  80, NULL, 0, {{0, 0}, {0, 0}, {0, 0}, {0, 0}, {0, 0}, {0, 0}, {0, 0}, {0, 0}},
  NULL, NULL, NULL, NULL},
{"verbosity", "int", "1", "", "",
  "",
  15,TRICK_INTEGER, sizeof(int), 0, 0, Language_CPP, 0,
  88, NULL, 0, {{0, 0}, {0, 0}, {0, 0}, {0, 0}, {0, 0}, {0, 0}, {0, 0}, {0, 0}},
  NULL, NULL, NULL, NULL},
{"integ_constructor", "er7_utils::IntegratorConstructor", "1", "", "",
  "n The integrator constructor that is used to generate the integration controls for this object and is used to generate the state integrators for each integrated object whose state is integrated by this group.",
  15,TRICK_STRUCTURED, 0, 0, 0, Language_CPP, 4,
  120, NULL, 1, {{0, 0}, {0, 0}, {0, 0}, {0, 0}, {0, 0}, {0, 0}, {0, 0}, {0, 0}},
  NULL, NULL, NULL, NULL},
{"integ_interface", "er7_utils::IntegratorInterface", "1", "", "",
  "n The interface between the integration module and the simulation engine's integration structure.",
  15,TRICK_STRUCTURED, 0, 0, 0, Language_CPP, 4,
  128, NULL, 1, {{0, 0}, {0, 0}, {0, 0}, {0, 0}, {0, 0}, {0, 0}, {0, 0}, {0, 0}},
  NULL, NULL, NULL, NULL},
{"time_interface", "er7_utils::TimeInterface", "1", "", "",
  "n The interface between the integration module and the object that represents time.",
  15,TRICK_STRUCTURED, 0, 0, 0, Language_CPP, 4,
  136, NULL, 1, {{0, 0}, {0, 0}, {0, 0}, {0, 0}, {0, 0}, {0, 0}, {0, 0}, {0, 0}},
  NULL, NULL, NULL, NULL},
{"integ_controls", "er7_utils::IntegrationControls", "1", "", "",
  "n The integration controls object that guides the integration process. This object is created at construction time by calling the integrator constructor's create_integration_controls method.",
  15,TRICK_STRUCTURED, 0, 0, 0, Language_CPP, 4,
  144, NULL, 1, {{0, 0}, {0, 0}, {0, 0}, {0, 0}, {0, 0}, {0, 0}, {0, 0}, {0, 0}},
  NULL, NULL, NULL, NULL},
{"cached_derivs", "double", "1", "", "",
  "n Vector of derivatives used to communicate between integrate_1st_order_ode and integrate_bodies.",
  15,TRICK_DOUBLE, sizeof(double), 0, 0, Language_CPP, 4,
  152, NULL, 1, {{0, 0}, {0, 0}, {0, 0}, {0, 0}, {0, 0}, {0, 0}, {0, 0}, {0, 0}},
  NULL, NULL, NULL, NULL},
{"cached_state", "double", "1", "", "",
  "n State vector used to communicate between integrate_1st_order_ode and integrate_bodies.",
  15,TRICK_DOUBLE, sizeof(double), 0, 0, Language_CPP, 4,
  160, NULL, 1, {{0, 0}, {0, 0}, {0, 0}, {0, 0}, {0, 0}, {0, 0}, {0, 0}, {0, 0}},
  NULL, NULL, NULL, NULL},
{"cached_accel", "double", "1", "", "",
  "n Vector of accelerations used to communicate between integrate_2nd_order_ode and integrate_bodies.",
  15,TRICK_DOUBLE, sizeof(double), 0, 0, Language_CPP, 4,
  168, NULL, 1, {{0, 0}, {0, 0}, {0, 0}, {0, 0}, {0, 0}, {0, 0}, {0, 0}, {0, 0}},
  NULL, NULL, NULL, NULL},
{"cached_velocity", "double", "1", "", "",
  "n Vector of velocities used to communicate between integrate_2nd_order_ode and integrate_bodies.",
  15,TRICK_DOUBLE, sizeof(double), 0, 0, Language_CPP, 4,
  176, NULL, 1, {{0, 0}, {0, 0}, {0, 0}, {0, 0}, {0, 0}, {0, 0}, {0, 0}, {0, 0}},
  NULL, NULL, NULL, NULL},
{"cached_position", "double", "1", "", "",
  "n Vector of positions used to communicate between integrate_2nd_order_ode and integrate_bodies.",
  15,TRICK_DOUBLE, sizeof(double), 0, 0, Language_CPP, 4,
  184, NULL, 1, {{0, 0}, {0, 0}, {0, 0}, {0, 0}, {0, 0}, {0, 0}, {0, 0}, {0, 0}},
  NULL, NULL, NULL, NULL},
{"er7_deriv", "double", "1", "", "",
  "n Allocated array of size buf_size used to trick out Trick's load_deriv.",
  15,TRICK_DOUBLE, sizeof(double), 0, 0, Language_CPP, 4,
  192, NULL, 1, {{0, 0}, {0, 0}, {0, 0}, {0, 0}, {0, 0}, {0, 0}, {0, 0}, {0, 0}},
  NULL, NULL, NULL, NULL},
{"er7_deriv2", "double", "1", "", "",
  "n Allocated array of size buf_size used to trick out Trick's load_deriv2.",
  15,TRICK_DOUBLE, sizeof(double), 0, 0, Language_CPP, 4,
  200, NULL, 1, {{0, 0}, {0, 0}, {0, 0}, {0, 0}, {0, 0}, {0, 0}, {0, 0}, {0, 0}},
  NULL, NULL, NULL, NULL},
{"trick_integ_constructor", "er7_utils::IntegratorConstructor", "1", "", "",
  "n The integrator constructor used to generate the state integrators this object.",
  15,TRICK_STRUCTURED, 0, 0, 0, Language_CPP, 4,
  208, NULL, 1, {{0, 0}, {0, 0}, {0, 0}, {0, 0}, {0, 0}, {0, 0}, {0, 0}, {0, 0}},
  NULL, NULL, NULL, NULL},
{"first_order_integrator", "er7_utils::FirstOrderODEIntegrator", "1", "", "",
  "n The integrator that propagates state as a first order ODE.",
  15,TRICK_STRUCTURED, 0, 0, 0, Language_CPP, 4,
  216, NULL, 1, {{0, 0}, {0, 0}, {0, 0}, {0, 0}, {0, 0}, {0, 0}, {0, 0}, {0, 0}},
  NULL, NULL, NULL, NULL},
{"second_order_integrator", "er7_utils::SecondOrderODEIntegrator", "1", "", "",
  "n The integrator that propagates state as a second order ODE.",
  15,TRICK_STRUCTURED, 0, 0, 0, Language_CPP, 4,
  224, NULL, 1, {{0, 0}, {0, 0}, {0, 0}, {0, 0}, {0, 0}, {0, 0}, {0, 0}, {0, 0}},
  NULL, NULL, NULL, NULL},
{"buf_size", "unsigned int", "1", "", "",
  "n Number of elements in the Trick::Integration group arrays.",
  15,TRICK_UNSIGNED_INTEGER, sizeof(unsigned int), 0, 0, Language_CPP, 4,
  232, NULL, 0, {{0, 0}, {0, 0}, {0, 0}, {0, 0}, {0, 0}, {0, 0}, {0, 0}, {0, 0}},
  NULL, NULL, NULL, NULL},
{"half_state_size", "int", "1", "", "",
  "n Number of elements in the Trick::Integration group arrays.",
  15,TRICK_INTEGER, sizeof(int), 0, 0, Language_CPP, 4,
  236, NULL, 0, {{0, 0}, {0, 0}, {0, 0}, {0, 0}, {0, 0}, {0, 0}, {0, 0}, {0, 0}},
  NULL, NULL, NULL, NULL},
{"integ_mode", "er7_utils::TrickIntegrator::IntegrationMode", "1", "", "",
  "n Indicates which of the first or second order integrator is to be used.",
  15,TRICK_ENUMERATED, 0, 0, 0, Language_CPP, 4,
  240, NULL, 0, {{0, 0}, {0, 0}, {0, 0}, {0, 0}, {0, 0}, {0, 0}, {0, 0}, {0, 0}},
  NULL, NULL, NULL, NULL},
{"default_first_step_deriv", "bool", "1", "", "",
  "n Default value of the Trick::Integrator first_step_deriv flag.",
  15,TRICK_BOOLEAN, sizeof(bool), 0, 0, Language_CPP, 4,
  244, NULL, 0, {{0, 0}, {0, 0}, {0, 0}, {0, 0}, {0, 0}, {0, 0}, {0, 0}, {0, 0}},
  NULL, NULL, NULL, NULL},
{"", "", "1", "", "",
  "",
  15,TRICK_VOID, 0, 0, 0, Language_CPP, 0,
  0, NULL, 0, {{0, 0}, {0, 0}, {0, 0}, {0, 0}, {0, 0}, {0, 0}, {0, 0}, {0, 0}},
  NULL, NULL, NULL, NULL} };

} //extern "C"

namespace er7_utils {

void init_attrer7_utils__TrickSecondOrderOdeIntegrator() {

    static int initialized ;
    if (initialized) {
        return;
    }
    initialized = 1;

    trick_MM->add_attr_info(std::string(attrer7_utils__TrickSecondOrderOdeIntegrator[15].type_name) , &attrer7_utils__TrickSecondOrderOdeIntegrator[15], __FILE__ , __LINE__ ) ;
    trick_MM->add_attr_info(std::string(attrer7_utils__TrickSecondOrderOdeIntegrator[16].type_name) , &attrer7_utils__TrickSecondOrderOdeIntegrator[16], __FILE__ , __LINE__ ) ;
    trick_MM->add_attr_info(std::string(attrer7_utils__TrickSecondOrderOdeIntegrator[17].type_name) , &attrer7_utils__TrickSecondOrderOdeIntegrator[17], __FILE__ , __LINE__ ) ;
    trick_MM->add_attr_info(std::string(attrer7_utils__TrickSecondOrderOdeIntegrator[18].type_name) , &attrer7_utils__TrickSecondOrderOdeIntegrator[18], __FILE__ , __LINE__ ) ;
    trick_MM->add_attr_info(std::string(attrer7_utils__TrickSecondOrderOdeIntegrator[26].type_name) , &attrer7_utils__TrickSecondOrderOdeIntegrator[26], __FILE__ , __LINE__ ) ;
    trick_MM->add_attr_info(std::string(attrer7_utils__TrickSecondOrderOdeIntegrator[27].type_name) , &attrer7_utils__TrickSecondOrderOdeIntegrator[27], __FILE__ , __LINE__ ) ;
    trick_MM->add_attr_info(std::string(attrer7_utils__TrickSecondOrderOdeIntegrator[28].type_name) , &attrer7_utils__TrickSecondOrderOdeIntegrator[28], __FILE__ , __LINE__ ) ;
    trick_MM->add_attr_info(std::string(attrer7_utils__TrickSecondOrderOdeIntegrator[31].type_name) , &attrer7_utils__TrickSecondOrderOdeIntegrator[31], __FILE__ , __LINE__ ) ;

    ATTRIBUTES temp_attr ;

    trick_MM->add_attr_info( std::string("er7_utils::TrickIntegrator"), &temp_attr , __FILE__ , __LINE__ ) ;
}
}

extern "C" {

void init_attrer7_utils__TrickSecondOrderOdeIntegrator_c_intf() {
    er7_utils::init_attrer7_utils__TrickSecondOrderOdeIntegrator() ;
}

size_t io_src_sizeof_er7_utils__TrickSecondOrderOdeIntegrator() {
    return sizeof(er7_utils::TrickSecondOrderOdeIntegrator) ;
}

void* io_src_allocate_er7_utils__TrickSecondOrderOdeIntegrator(int num) {
    er7_utils::TrickSecondOrderOdeIntegrator* temp = (er7_utils::TrickSecondOrderOdeIntegrator*)calloc(num, sizeof(er7_utils::TrickSecondOrderOdeIntegrator));
    for (int ii = 0; ii < num; ++ii) {
        new(&temp[ii]) er7_utils::TrickSecondOrderOdeIntegrator();
    }
    return (void*)temp;
}

void io_src_destruct_er7_utils__TrickSecondOrderOdeIntegrator(void* address __attribute__((unused)), int num __attribute__((unused))) {
    using namespace er7_utils;
    er7_utils::TrickSecondOrderOdeIntegrator* temp = (er7_utils::TrickSecondOrderOdeIntegrator*)address;
    for (int ii = 0; ii < num; ++ii) {
        temp[ii].~TrickSecondOrderOdeIntegrator();
    }
}

void io_src_delete_er7_utils__TrickSecondOrderOdeIntegrator(void* address) {
    delete (er7_utils::TrickSecondOrderOdeIntegrator*)address;
}

} //extern "C"

struct UnitsMaper7_utils__TrickSecondOrderOdeIntegrator {
    UnitsMaper7_utils__TrickSecondOrderOdeIntegrator() {
        Trick::UnitsMap* units_map_ptr = Trick::UnitsMap::units_map();
        units_map_ptr->add_param("TrickSecondOrderOdeIntegrator_num_state", "1") ;
        units_map_ptr->add_param("TrickSecondOrderOdeIntegrator_intermediate_step", "1") ;
        units_map_ptr->add_param("TrickSecondOrderOdeIntegrator_first_step_deriv", "1") ;
        units_map_ptr->add_param("TrickSecondOrderOdeIntegrator_last_step_deriv", "1") ;
        units_map_ptr->add_param("TrickSecondOrderOdeIntegrator_is_2nd_order_ODE_technique", "1") ;
        units_map_ptr->add_param("TrickSecondOrderOdeIntegrator_use_deriv2", "1") ;
        units_map_ptr->add_param("TrickSecondOrderOdeIntegrator_dt", "1") ;
        units_map_ptr->add_param("TrickSecondOrderOdeIntegrator_target_integ_time", "1") ;
        units_map_ptr->add_param("TrickSecondOrderOdeIntegrator_state", "1") ;
        units_map_ptr->add_param("TrickSecondOrderOdeIntegrator_deriv", "1") ;
        units_map_ptr->add_param("TrickSecondOrderOdeIntegrator_deriv2", "1") ;
        units_map_ptr->add_param("TrickSecondOrderOdeIntegrator_state_ws", "1") ;
        units_map_ptr->add_param("TrickSecondOrderOdeIntegrator_time", "1") ;
        units_map_ptr->add_param("TrickSecondOrderOdeIntegrator_time_0", "1") ;
        units_map_ptr->add_param("TrickSecondOrderOdeIntegrator_verbosity", "1") ;
        units_map_ptr->add_param("TrickSecondOrderOdeIntegrator_integ_constructor", "1") ;
        units_map_ptr->add_param("TrickSecondOrderOdeIntegrator_integ_interface", "1") ;
        units_map_ptr->add_param("TrickSecondOrderOdeIntegrator_time_interface", "1") ;
        units_map_ptr->add_param("TrickSecondOrderOdeIntegrator_integ_controls", "1") ;
        units_map_ptr->add_param("TrickSecondOrderOdeIntegrator_cached_derivs", "1") ;
        units_map_ptr->add_param("TrickSecondOrderOdeIntegrator_cached_state", "1") ;
        units_map_ptr->add_param("TrickSecondOrderOdeIntegrator_cached_accel", "1") ;
        units_map_ptr->add_param("TrickSecondOrderOdeIntegrator_cached_velocity", "1") ;
        units_map_ptr->add_param("TrickSecondOrderOdeIntegrator_cached_position", "1") ;
        units_map_ptr->add_param("TrickSecondOrderOdeIntegrator_er7_deriv", "1") ;
        units_map_ptr->add_param("TrickSecondOrderOdeIntegrator_er7_deriv2", "1") ;
        units_map_ptr->add_param("TrickSecondOrderOdeIntegrator_trick_integ_constructor", "1") ;
        units_map_ptr->add_param("TrickSecondOrderOdeIntegrator_first_order_integrator", "1") ;
        units_map_ptr->add_param("TrickSecondOrderOdeIntegrator_second_order_integrator", "1") ;
        units_map_ptr->add_param("TrickSecondOrderOdeIntegrator_buf_size", "1") ;
        units_map_ptr->add_param("TrickSecondOrderOdeIntegrator_half_state_size", "1") ;
        units_map_ptr->add_param("TrickSecondOrderOdeIntegrator_integ_mode", "1") ;
        units_map_ptr->add_param("TrickSecondOrderOdeIntegrator_default_first_step_deriv", "1") ;
    }
} umer7_utils__TrickSecondOrderOdeIntegrator;

