/**
 * This file was automatically generated by the ICG based on the file:
 * /users/agirish/trick_tutorial/trick/trick_source/er7_utils/integration/core/include/base_integration_group.hh
 * This file contains database parameter declarations specific to the
 * data structures and enumerated types declared in the above file.
 * These database parameters are used by the Trick input and
 * data recording processors to gain access to important simulation
 * variable information.
 */

#define TRICK_IN_IOSRC
#include <stdlib.h>
#include "trick/MemoryManager.hh"
#include "trick/attributes.h"
#include "trick/parameter_types.h"
#include "trick/ClassSizeCheck.hh"
#include "trick/UnitsMap.hh"
#include "trick/checkpoint_stl.hh"
#include "/users/agirish/trick_tutorial/trick/trick_source/er7_utils/integration/core/include/base_integration_group.hh"

extern "C" {

ATTRIBUTES attrer7_utils__BaseIntegrationGroup[] = {
{"integ_constructor", "er7_utils::IntegratorConstructor", "1", "", "",
  "n The integrator constructor that is used to generate the integration controls for this object and is used to generate the state integrators for each integrated object whose state is integrated by this group.",
  15,TRICK_STRUCTURED, 0, 0, 0, Language_CPP, 4,
  8, NULL, 1, {{0, 0}, {0, 0}, {0, 0}, {0, 0}, {0, 0}, {0, 0}, {0, 0}, {0, 0}},
  NULL, NULL, NULL, NULL},
{"integ_interface", "er7_utils::IntegratorInterface", "1", "", "",
  "n The interface between the integration module and the simulation engine's integration structure.",
  15,TRICK_STRUCTURED, 0, 0, 0, Language_CPP, 4,
  16, NULL, 1, {{0, 0}, {0, 0}, {0, 0}, {0, 0}, {0, 0}, {0, 0}, {0, 0}, {0, 0}},
  NULL, NULL, NULL, NULL},
{"time_interface", "er7_utils::TimeInterface", "1", "", "",
  "n The interface between the integration module and the object that represents time.",
  15,TRICK_STRUCTURED, 0, 0, 0, Language_CPP, 4,
  24, NULL, 1, {{0, 0}, {0, 0}, {0, 0}, {0, 0}, {0, 0}, {0, 0}, {0, 0}, {0, 0}},
  NULL, NULL, NULL, NULL},
{"integ_controls", "er7_utils::IntegrationControls", "1", "", "",
  "n The integration controls object that guides the integration process. This object is created at construction time by calling the integrator constructor's create_integration_controls method.",
  15,TRICK_STRUCTURED, 0, 0, 0, Language_CPP, 4,
  32, NULL, 1, {{0, 0}, {0, 0}, {0, 0}, {0, 0}, {0, 0}, {0, 0}, {0, 0}, {0, 0}},
  NULL, NULL, NULL, NULL},
{"", "", "1", "", "",
  "",
  15,TRICK_VOID, 0, 0, 0, Language_CPP, 0,
  0, NULL, 0, {{0, 0}, {0, 0}, {0, 0}, {0, 0}, {0, 0}, {0, 0}, {0, 0}, {0, 0}},
  NULL, NULL, NULL, NULL} };

} //extern "C"

namespace er7_utils {

void init_attrer7_utils__BaseIntegrationGroup() {

    static int initialized ;
    if (initialized) {
        return;
    }
    initialized = 1;

    trick_MM->add_attr_info(std::string(attrer7_utils__BaseIntegrationGroup[0].type_name) , &attrer7_utils__BaseIntegrationGroup[0], __FILE__ , __LINE__ ) ;
    trick_MM->add_attr_info(std::string(attrer7_utils__BaseIntegrationGroup[1].type_name) , &attrer7_utils__BaseIntegrationGroup[1], __FILE__ , __LINE__ ) ;
    trick_MM->add_attr_info(std::string(attrer7_utils__BaseIntegrationGroup[2].type_name) , &attrer7_utils__BaseIntegrationGroup[2], __FILE__ , __LINE__ ) ;
    trick_MM->add_attr_info(std::string(attrer7_utils__BaseIntegrationGroup[3].type_name) , &attrer7_utils__BaseIntegrationGroup[3], __FILE__ , __LINE__ ) ;
}
}

extern "C" {

void init_attrer7_utils__BaseIntegrationGroup_c_intf() {
    er7_utils::init_attrer7_utils__BaseIntegrationGroup() ;
}

size_t io_src_sizeof_er7_utils__BaseIntegrationGroup() {
    return sizeof(er7_utils::BaseIntegrationGroup) ;
}

void io_src_destruct_er7_utils__BaseIntegrationGroup(void* address __attribute__((unused)), int num __attribute__((unused))) {
    using namespace er7_utils;
    er7_utils::BaseIntegrationGroup* temp = (er7_utils::BaseIntegrationGroup*)address;
    for (int ii = 0; ii < num; ++ii) {
        temp[ii].~BaseIntegrationGroup();
    }
}

void io_src_delete_er7_utils__BaseIntegrationGroup(void* address) {
    delete (er7_utils::BaseIntegrationGroup*)address;
}

} //extern "C"

struct UnitsMaper7_utils__BaseIntegrationGroup {
    UnitsMaper7_utils__BaseIntegrationGroup() {
        Trick::UnitsMap* units_map_ptr = Trick::UnitsMap::units_map();
        units_map_ptr->add_param("BaseIntegrationGroup_integ_constructor", "1") ;
        units_map_ptr->add_param("BaseIntegrationGroup_integ_interface", "1") ;
        units_map_ptr->add_param("BaseIntegrationGroup_time_interface", "1") ;
        units_map_ptr->add_param("BaseIntegrationGroup_integ_controls", "1") ;
    }
} umer7_utils__BaseIntegrationGroup;

