/**
 * This file was automatically generated by the ICG based on the file:
 * /users/agirish/trick_tutorial/trick/trick_source/er7_utils/integration/core/include/generalized_position_derivative.hh
 * This file contains database parameter declarations specific to the
 * data structures and enumerated types declared in the above file.
 * These database parameters are used by the Trick input and
 * data recording processors to gain access to important simulation
 * variable information.
 */

#define TRICK_IN_IOSRC
#include <stdlib.h>
#include "trick/MemoryManager.hh"
#include "trick/attributes.h"
#include "trick/parameter_types.h"
#include "trick/ClassSizeCheck.hh"
#include "trick/UnitsMap.hh"
#include "trick/checkpoint_stl.hh"
#include "/users/agirish/trick_tutorial/trick/trick_source/er7_utils/integration/core/include/generalized_position_derivative.hh"

extern "C" {

ATTRIBUTES attrer7_utils__GeneralizedPositionDerivativeFunctions[] = {
{"", "", "1", "", "",
  "",
  15,TRICK_VOID, 0, 0, 0, Language_CPP, 0,
  0, NULL, 0, {{0, 0}, {0, 0}, {0, 0}, {0, 0}, {0, 0}, {0, 0}, {0, 0}, {0, 0}},
  NULL, NULL, NULL, NULL} };

} //extern "C"

namespace er7_utils {

void init_attrer7_utils__GeneralizedPositionDerivativeFunctions() {

    static int initialized ;
    if (initialized) {
        return;
    }
    initialized = 1;

}
}

extern "C" {

void init_attrer7_utils__GeneralizedPositionDerivativeFunctions_c_intf() {
    er7_utils::init_attrer7_utils__GeneralizedPositionDerivativeFunctions() ;
}

size_t io_src_sizeof_er7_utils__GeneralizedPositionDerivativeFunctions() {
    return sizeof(er7_utils::GeneralizedPositionDerivativeFunctions) ;
}

void* io_src_allocate_er7_utils__GeneralizedPositionDerivativeFunctions(int num) {
    er7_utils::GeneralizedPositionDerivativeFunctions* temp = (er7_utils::GeneralizedPositionDerivativeFunctions*)calloc(num, sizeof(er7_utils::GeneralizedPositionDerivativeFunctions));
    for (int ii = 0; ii < num; ++ii) {
        new(&temp[ii]) er7_utils::GeneralizedPositionDerivativeFunctions();
    }
    return (void*)temp;
}

void io_src_destruct_er7_utils__GeneralizedPositionDerivativeFunctions(void* address __attribute__((unused)), int num __attribute__((unused))) {
    using namespace er7_utils;
    er7_utils::GeneralizedPositionDerivativeFunctions* temp = (er7_utils::GeneralizedPositionDerivativeFunctions*)address;
    for (int ii = 0; ii < num; ++ii) {
        temp[ii].~GeneralizedPositionDerivativeFunctions();
    }
}

void io_src_delete_er7_utils__GeneralizedPositionDerivativeFunctions(void* address) {
    delete (er7_utils::GeneralizedPositionDerivativeFunctions*)address;
}

} //extern "C"

struct UnitsMaper7_utils__GeneralizedPositionDerivativeFunctions {
} umer7_utils__GeneralizedPositionDerivativeFunctions;

extern "C" {

ATTRIBUTES attrer7_utils__GeneralizedPositionStepFunctions[] = {
{"", "", "1", "", "",
  "",
  15,TRICK_VOID, 0, 0, 0, Language_CPP, 0,
  0, NULL, 0, {{0, 0}, {0, 0}, {0, 0}, {0, 0}, {0, 0}, {0, 0}, {0, 0}, {0, 0}},
  NULL, NULL, NULL, NULL} };

} //extern "C"

namespace er7_utils {

void init_attrer7_utils__GeneralizedPositionStepFunctions() {

    static int initialized ;
    if (initialized) {
        return;
    }
    initialized = 1;

}
}

extern "C" {

void init_attrer7_utils__GeneralizedPositionStepFunctions_c_intf() {
    er7_utils::init_attrer7_utils__GeneralizedPositionStepFunctions() ;
}

size_t io_src_sizeof_er7_utils__GeneralizedPositionStepFunctions() {
    return sizeof(er7_utils::GeneralizedPositionStepFunctions) ;
}

void* io_src_allocate_er7_utils__GeneralizedPositionStepFunctions(int num) {
    er7_utils::GeneralizedPositionStepFunctions* temp = (er7_utils::GeneralizedPositionStepFunctions*)calloc(num, sizeof(er7_utils::GeneralizedPositionStepFunctions));
    for (int ii = 0; ii < num; ++ii) {
        new(&temp[ii]) er7_utils::GeneralizedPositionStepFunctions();
    }
    return (void*)temp;
}

void io_src_destruct_er7_utils__GeneralizedPositionStepFunctions(void* address __attribute__((unused)), int num __attribute__((unused))) {
    using namespace er7_utils;
    er7_utils::GeneralizedPositionStepFunctions* temp = (er7_utils::GeneralizedPositionStepFunctions*)address;
    for (int ii = 0; ii < num; ++ii) {
        temp[ii].~GeneralizedPositionStepFunctions();
    }
}

void io_src_delete_er7_utils__GeneralizedPositionStepFunctions(void* address) {
    delete (er7_utils::GeneralizedPositionStepFunctions*)address;
}

} //extern "C"

struct UnitsMaper7_utils__GeneralizedPositionStepFunctions {
} umer7_utils__GeneralizedPositionStepFunctions;

