/**
 * This file was automatically generated by the ICG based on the file:
 * /users/agirish/trick_tutorial/trick/trick_source/er7_utils/integration/core/include/integrator_constructor_factory.hh
 * This file contains database parameter declarations specific to the
 * data structures and enumerated types declared in the above file.
 * These database parameters are used by the Trick input and
 * data recording processors to gain access to important simulation
 * variable information.
 */

#define TRICK_IN_IOSRC
#include <stdlib.h>
#include "trick/MemoryManager.hh"
#include "trick/attributes.h"
#include "trick/parameter_types.h"
#include "trick/ClassSizeCheck.hh"
#include "trick/UnitsMap.hh"
#include "trick/checkpoint_stl.hh"
#include "/users/agirish/trick_tutorial/trick/trick_source/er7_utils/integration/core/include/integrator_constructor_factory.hh"

extern "C" {

ATTRIBUTES attrer7_utils__IntegratorConstructorFactory[] = {
{"", "", "1", "", "",
  "",
  15,TRICK_VOID, 0, 0, 0, Language_CPP, 0,
  0, NULL, 0, {{0, 0}, {0, 0}, {0, 0}, {0, 0}, {0, 0}, {0, 0}, {0, 0}, {0, 0}},
  NULL, NULL, NULL, NULL} };

} //extern "C"

namespace er7_utils {

void init_attrer7_utils__IntegratorConstructorFactory() {

    static int initialized ;
    if (initialized) {
        return;
    }
    initialized = 1;

}
}

extern "C" {

void init_attrer7_utils__IntegratorConstructorFactory_c_intf() {
    er7_utils::init_attrer7_utils__IntegratorConstructorFactory() ;
}

size_t io_src_sizeof_er7_utils__IntegratorConstructorFactory() {
    return sizeof(er7_utils::IntegratorConstructorFactory) ;
}


} //extern "C"

struct UnitsMaper7_utils__IntegratorConstructorFactory {
} umer7_utils__IntegratorConstructorFactory;

