/**
 * This file was automatically generated by the ICG based on the file:
 * /users/agirish/trick_tutorial/trick/trick_source/er7_utils/integration/core/include/integration_technique.hh
 * This file contains database parameter declarations specific to the
 * data structures and enumerated types declared in the above file.
 * These database parameters are used by the Trick input and
 * data recording processors to gain access to important simulation
 * variable information.
 */

#define TRICK_IN_IOSRC
#include <stdlib.h>
#include "trick/MemoryManager.hh"
#include "trick/attributes.h"
#include "trick/parameter_types.h"
#include "trick/ClassSizeCheck.hh"
#include "trick/UnitsMap.hh"
#include "trick/checkpoint_stl.hh"
#include "/users/agirish/trick_tutorial/trick/trick_source/er7_utils/integration/core/include/integration_technique.hh"

extern "C" {

ENUM_ATTR enumer7_utils__Integration__Technique[] = {
{"er7_utils::Integration::Unspecified", 0, 0x0},
{"er7_utils::Integration::Euler", 1, 0x0},
{"er7_utils::Integration::SymplecticEuler", 2, 0x0},
{"er7_utils::Integration::Beeman", 11, 0x0},
{"er7_utils::Integration::NystromLear2", 14, 0x0},
{"er7_utils::Integration::PositionVerlet", 15, 0x0},
{"er7_utils::Integration::RK2Heun", 16, 0x0},
{"er7_utils::Integration::RK2Midpoint", 17, 0x0},
{"er7_utils::Integration::VelocityVerlet", 19, 0x0},
{"er7_utils::Integration::ModifiedMidpoint4", 21, 0x0},
{"er7_utils::Integration::AdamsBashforthMoulton4", 31, 0x0},
{"er7_utils::Integration::RungeKutta4", 34, 0x0},
{"er7_utils::Integration::RKGill4", 35, 0x0},
{"er7_utils::Integration::RKNystrom4", 36, 0x0},
{"er7_utils::Integration::RKFehlberg45", 44, 0x0},
{"er7_utils::Integration::RKFehlberg78", 74, 0x0},
{"er7_utils::Integration::Unsupported", 998, 0x0},
{"er7_utils::Integration::Invalid", 999, 0x0},
{"", 0, 0x0}
};

} //extern "C"

extern "C" {

size_t io_src_sizeof_er7_utils__Integration__Technique( void ) {
    return sizeof(er7_utils::Integration::Technique);
}

} //extern "C"

extern "C" {

ENUM_ATTR enumer7_utils__Integration__ODEProblemType[] = {
{"er7_utils::Integration::FirstOrderODE", 0, 0x0},
{"er7_utils::Integration::SimpleSecondOrderODE", 1, 0x0},
{"er7_utils::Integration::GeneralizedDerivSecondOrderODE", 2, 0x0},
{"er7_utils::Integration::GeneralizedStepSecondOrderODE", 3, 0x0},
{"", 0, 0x0}
};

} //extern "C"

extern "C" {

size_t io_src_sizeof_er7_utils__Integration__ODEProblemType( void ) {
    return sizeof(er7_utils::Integration::ODEProblemType);
}

} //extern "C"

extern "C" {

ATTRIBUTES attrer7_utils__Integration[] = {
{"", "", "1", "", "",
  "",
  15,TRICK_VOID, 0, 0, 0, Language_CPP, 0,
  0, NULL, 0, {{0, 0}, {0, 0}, {0, 0}, {0, 0}, {0, 0}, {0, 0}, {0, 0}, {0, 0}},
  NULL, NULL, NULL, NULL} };

} //extern "C"

namespace er7_utils {

void init_attrer7_utils__Integration() {

    static int initialized ;
    if (initialized) {
        return;
    }
    initialized = 1;

}
}

extern "C" {

void init_attrer7_utils__Integration_c_intf() {
    er7_utils::init_attrer7_utils__Integration() ;
}

size_t io_src_sizeof_er7_utils__Integration() {
    return sizeof(er7_utils::Integration) ;
}


} //extern "C"

struct UnitsMaper7_utils__Integration {
} umer7_utils__Integration;

