/**
 * This file was automatically generated by the ICG based on the file:
 * /users/agirish/trick_tutorial/trick/trick_source/er7_utils/integration/core/include/left_quaternion_functions.hh
 * This file contains database parameter declarations specific to the
 * data structures and enumerated types declared in the above file.
 * These database parameters are used by the Trick input and
 * data recording processors to gain access to important simulation
 * variable information.
 */

#define TRICK_IN_IOSRC
#include <stdlib.h>
#include "trick/MemoryManager.hh"
#include "trick/attributes.h"
#include "trick/parameter_types.h"
#include "trick/ClassSizeCheck.hh"
#include "trick/UnitsMap.hh"
#include "trick/checkpoint_stl.hh"
#include "/users/agirish/trick_tutorial/trick/trick_source/er7_utils/integration/core/include/left_quaternion_functions.hh"

extern "C" {

ATTRIBUTES attrer7_utils__LeftQuaternionGeneralizedPositionDerivativeFunctions[] = {
{"", "", "1", "", "",
  "",
  15,TRICK_VOID, 0, 0, 0, Language_CPP, 0,
  0, NULL, 0, {{0, 0}, {0, 0}, {0, 0}, {0, 0}, {0, 0}, {0, 0}, {0, 0}, {0, 0}},
  NULL, NULL, NULL, NULL} };

} //extern "C"

namespace er7_utils {

void init_attrer7_utils__LeftQuaternionGeneralizedPositionDerivativeFunctions() {

    static int initialized ;
    if (initialized) {
        return;
    }
    initialized = 1;


    ATTRIBUTES temp_attr ;

    trick_MM->add_attr_info( std::string("er7_utils::GeneralizedPositionDerivativeFunctions"), &temp_attr , __FILE__ , __LINE__ ) ;
}
}

extern "C" {

void init_attrer7_utils__LeftQuaternionGeneralizedPositionDerivativeFunctions_c_intf() {
    er7_utils::init_attrer7_utils__LeftQuaternionGeneralizedPositionDerivativeFunctions() ;
}

size_t io_src_sizeof_er7_utils__LeftQuaternionGeneralizedPositionDerivativeFunctions() {
    return sizeof(er7_utils::LeftQuaternionGeneralizedPositionDerivativeFunctions) ;
}

void* io_src_allocate_er7_utils__LeftQuaternionGeneralizedPositionDerivativeFunctions(int num) {
    er7_utils::LeftQuaternionGeneralizedPositionDerivativeFunctions* temp = (er7_utils::LeftQuaternionGeneralizedPositionDerivativeFunctions*)calloc(num, sizeof(er7_utils::LeftQuaternionGeneralizedPositionDerivativeFunctions));
    for (int ii = 0; ii < num; ++ii) {
        new(&temp[ii]) er7_utils::LeftQuaternionGeneralizedPositionDerivativeFunctions();
    }
    return (void*)temp;
}

void io_src_destruct_er7_utils__LeftQuaternionGeneralizedPositionDerivativeFunctions(void* address __attribute__((unused)), int num __attribute__((unused))) {
    using namespace er7_utils;
    er7_utils::LeftQuaternionGeneralizedPositionDerivativeFunctions* temp = (er7_utils::LeftQuaternionGeneralizedPositionDerivativeFunctions*)address;
    for (int ii = 0; ii < num; ++ii) {
        temp[ii].~LeftQuaternionGeneralizedPositionDerivativeFunctions();
    }
}

void io_src_delete_er7_utils__LeftQuaternionGeneralizedPositionDerivativeFunctions(void* address) {
    delete (er7_utils::LeftQuaternionGeneralizedPositionDerivativeFunctions*)address;
}

} //extern "C"

struct UnitsMaper7_utils__LeftQuaternionGeneralizedPositionDerivativeFunctions {
} umer7_utils__LeftQuaternionGeneralizedPositionDerivativeFunctions;

extern "C" {

ATTRIBUTES attrer7_utils__LeftQuaternionGeneralizedPositionStepFunctions[] = {
{"", "", "1", "", "",
  "",
  15,TRICK_VOID, 0, 0, 0, Language_CPP, 0,
  0, NULL, 0, {{0, 0}, {0, 0}, {0, 0}, {0, 0}, {0, 0}, {0, 0}, {0, 0}, {0, 0}},
  NULL, NULL, NULL, NULL} };

} //extern "C"

namespace er7_utils {

void init_attrer7_utils__LeftQuaternionGeneralizedPositionStepFunctions() {

    static int initialized ;
    if (initialized) {
        return;
    }
    initialized = 1;


    ATTRIBUTES temp_attr ;

    trick_MM->add_attr_info( std::string("er7_utils::GeneralizedPositionStepFunctions"), &temp_attr , __FILE__ , __LINE__ ) ;
}
}

extern "C" {

void init_attrer7_utils__LeftQuaternionGeneralizedPositionStepFunctions_c_intf() {
    er7_utils::init_attrer7_utils__LeftQuaternionGeneralizedPositionStepFunctions() ;
}

size_t io_src_sizeof_er7_utils__LeftQuaternionGeneralizedPositionStepFunctions() {
    return sizeof(er7_utils::LeftQuaternionGeneralizedPositionStepFunctions) ;
}

void* io_src_allocate_er7_utils__LeftQuaternionGeneralizedPositionStepFunctions(int num) {
    er7_utils::LeftQuaternionGeneralizedPositionStepFunctions* temp = (er7_utils::LeftQuaternionGeneralizedPositionStepFunctions*)calloc(num, sizeof(er7_utils::LeftQuaternionGeneralizedPositionStepFunctions));
    for (int ii = 0; ii < num; ++ii) {
        new(&temp[ii]) er7_utils::LeftQuaternionGeneralizedPositionStepFunctions();
    }
    return (void*)temp;
}

void io_src_destruct_er7_utils__LeftQuaternionGeneralizedPositionStepFunctions(void* address __attribute__((unused)), int num __attribute__((unused))) {
    using namespace er7_utils;
    er7_utils::LeftQuaternionGeneralizedPositionStepFunctions* temp = (er7_utils::LeftQuaternionGeneralizedPositionStepFunctions*)address;
    for (int ii = 0; ii < num; ++ii) {
        temp[ii].~LeftQuaternionGeneralizedPositionStepFunctions();
    }
}

void io_src_delete_er7_utils__LeftQuaternionGeneralizedPositionStepFunctions(void* address) {
    delete (er7_utils::LeftQuaternionGeneralizedPositionStepFunctions*)address;
}

} //extern "C"

struct UnitsMaper7_utils__LeftQuaternionGeneralizedPositionStepFunctions {
} umer7_utils__LeftQuaternionGeneralizedPositionStepFunctions;

extern "C" {

ATTRIBUTES attrer7_utils__LeftQuaternionGeneralizedPositionFunctions[] = {
{"", "", "1", "", "",
  "",
  15,TRICK_VOID, 0, 0, 0, Language_CPP, 0,
  0, NULL, 0, {{0, 0}, {0, 0}, {0, 0}, {0, 0}, {0, 0}, {0, 0}, {0, 0}, {0, 0}},
  NULL, NULL, NULL, NULL} };

} //extern "C"

namespace er7_utils {

void init_attrer7_utils__LeftQuaternionGeneralizedPositionFunctions() {

    static int initialized ;
    if (initialized) {
        return;
    }
    initialized = 1;


    ATTRIBUTES temp_attr ;

    trick_MM->add_attr_info( std::string("er7_utils::LeftQuaternionGeneralizedPositionDerivativeFunctions"), &temp_attr , __FILE__ , __LINE__ ) ;
    trick_MM->add_attr_info( std::string("er7_utils::LeftQuaternionGeneralizedPositionStepFunctions"), &temp_attr , __FILE__ , __LINE__ ) ;
}
}

extern "C" {

void init_attrer7_utils__LeftQuaternionGeneralizedPositionFunctions_c_intf() {
    er7_utils::init_attrer7_utils__LeftQuaternionGeneralizedPositionFunctions() ;
}

size_t io_src_sizeof_er7_utils__LeftQuaternionGeneralizedPositionFunctions() {
    return sizeof(er7_utils::LeftQuaternionGeneralizedPositionFunctions) ;
}

void* io_src_allocate_er7_utils__LeftQuaternionGeneralizedPositionFunctions(int num) {
    er7_utils::LeftQuaternionGeneralizedPositionFunctions* temp = (er7_utils::LeftQuaternionGeneralizedPositionFunctions*)calloc(num, sizeof(er7_utils::LeftQuaternionGeneralizedPositionFunctions));
    for (int ii = 0; ii < num; ++ii) {
        new(&temp[ii]) er7_utils::LeftQuaternionGeneralizedPositionFunctions();
    }
    return (void*)temp;
}

void io_src_destruct_er7_utils__LeftQuaternionGeneralizedPositionFunctions(void* address __attribute__((unused)), int num __attribute__((unused))) {
    using namespace er7_utils;
    er7_utils::LeftQuaternionGeneralizedPositionFunctions* temp = (er7_utils::LeftQuaternionGeneralizedPositionFunctions*)address;
    for (int ii = 0; ii < num; ++ii) {
        temp[ii].~LeftQuaternionGeneralizedPositionFunctions();
    }
}

void io_src_delete_er7_utils__LeftQuaternionGeneralizedPositionFunctions(void* address) {
    delete (er7_utils::LeftQuaternionGeneralizedPositionFunctions*)address;
}

} //extern "C"

struct UnitsMaper7_utils__LeftQuaternionGeneralizedPositionFunctions {
} umer7_utils__LeftQuaternionGeneralizedPositionFunctions;

