/**
 * This file was automatically generated by the ICG based on the file:
 * /users/agirish/trick_tutorial/trick/trick_source/er7_utils/integration/core/include/priming_second_order_ode_integrator.hh
 * This file contains database parameter declarations specific to the
 * data structures and enumerated types declared in the above file.
 * These database parameters are used by the Trick input and
 * data recording processors to gain access to important simulation
 * variable information.
 */

#define TRICK_IN_IOSRC
#include <stdlib.h>
#include "trick/MemoryManager.hh"
#include "trick/attributes.h"
#include "trick/parameter_types.h"
#include "trick/ClassSizeCheck.hh"
#include "trick/UnitsMap.hh"
#include "trick/checkpoint_stl.hh"
#include "/users/agirish/trick_tutorial/trick/trick_source/er7_utils/integration/core/include/priming_second_order_ode_integrator.hh"

extern "C" {

ATTRIBUTES attrer7_utils__PrimingSecondOrderODEIntegrator[] = {
{"state_size", "int", "1", "", "",
  "n The sizes of the generalized position and generalized velocity vectors.",
  15,TRICK_INTEGER, sizeof(int), 0, 0, Language_CPP, 4,
  40, NULL, 1, {{2, 0}, {0, 0}, {0, 0}, {0, 0}, {0, 0}, {0, 0}, {0, 0}, {0, 0}},
  NULL, NULL, NULL, NULL},
{"problem_type", "er7_utils::Integration::ODEProblemType", "1", "", "",
  "n The type of problem to be solved.",
  15,TRICK_ENUMERATED, 0, 0, 0, Language_CPP, 4,
  48, NULL, 0, {{0, 0}, {0, 0}, {0, 0}, {0, 0}, {0, 0}, {0, 0}, {0, 0}, {0, 0}},
  NULL, NULL, NULL, NULL},
{"controls", "er7_utils::IntegrationControls", "1", "", "",
  "n The integration controls object that controls this state integrator.",
  15,TRICK_STRUCTURED, 0, 0, 0, Language_CPP, 4,
  56, NULL, 1, {{0, 0}, {0, 0}, {0, 0}, {0, 0}, {0, 0}, {0, 0}, {0, 0}, {0, 0}},
  NULL, NULL, NULL, NULL},
{"primer", "er7_utils::SecondOrderODEIntegrator", "1", "", "",
  "n The state integrator used to prime this integrator.",
  15,TRICK_STRUCTURED, 0, 0, 0, Language_CPP, 4,
  64, NULL, 1, {{0, 0}, {0, 0}, {0, 0}, {0, 0}, {0, 0}, {0, 0}, {0, 0}, {0, 0}},
  NULL, NULL, NULL, NULL},
{"priming_state_size", "int", "1", "", "",
  "n The number of start of cycle derivatives needed by the technique.",
  15,TRICK_INTEGER, sizeof(int), 0, 0, Language_CPP, 4,
  72, NULL, 0, {{0, 0}, {0, 0}, {0, 0}, {0, 0}, {0, 0}, {0, 0}, {0, 0}, {0, 0}},
  NULL, NULL, NULL, NULL},
{"prime_counter", "int", "1", "", "",
  "n Priming phase countdown. This is set to priming_state_size initially and upon reset. Priming is complete when the counter reaches zero.",
  15,TRICK_INTEGER, sizeof(int), 0, 0, Language_CPP, 4,
  76, NULL, 0, {{0, 0}, {0, 0}, {0, 0}, {0, 0}, {0, 0}, {0, 0}, {0, 0}, {0, 0}},
  NULL, NULL, NULL, NULL},
{"primed", "bool", "1", "", "",
  "n Indicates whether the object has been primed. This is false initially and upon reset; it is set to true when priming is complete.",
  15,TRICK_BOOLEAN, sizeof(bool), 0, 0, Language_CPP, 4,
  80, NULL, 0, {{0, 0}, {0, 0}, {0, 0}, {0, 0}, {0, 0}, {0, 0}, {0, 0}, {0, 0}},
  NULL, NULL, NULL, NULL},
{"", "", "1", "", "",
  "",
  15,TRICK_VOID, 0, 0, 0, Language_CPP, 0,
  0, NULL, 0, {{0, 0}, {0, 0}, {0, 0}, {0, 0}, {0, 0}, {0, 0}, {0, 0}, {0, 0}},
  NULL, NULL, NULL, NULL} };

} //extern "C"

namespace er7_utils {

void init_attrer7_utils__PrimingSecondOrderODEIntegrator() {

    static int initialized ;
    if (initialized) {
        return;
    }
    initialized = 1;

    trick_MM->add_attr_info(std::string(attrer7_utils__PrimingSecondOrderODEIntegrator[1].type_name) , &attrer7_utils__PrimingSecondOrderODEIntegrator[1], __FILE__ , __LINE__ ) ;
    trick_MM->add_attr_info(std::string(attrer7_utils__PrimingSecondOrderODEIntegrator[2].type_name) , &attrer7_utils__PrimingSecondOrderODEIntegrator[2], __FILE__ , __LINE__ ) ;
    trick_MM->add_attr_info(std::string(attrer7_utils__PrimingSecondOrderODEIntegrator[3].type_name) , &attrer7_utils__PrimingSecondOrderODEIntegrator[3], __FILE__ , __LINE__ ) ;

    ATTRIBUTES temp_attr ;

    trick_MM->add_attr_info( std::string("er7_utils::SecondOrderODEIntegrator"), &temp_attr , __FILE__ , __LINE__ ) ;
    trick_MM->add_attr_info( std::string("er7_utils::Er7UtilsDeletable"), &temp_attr , __FILE__ , __LINE__ ) ;
}
}

extern "C" {

void init_attrer7_utils__PrimingSecondOrderODEIntegrator_c_intf() {
    er7_utils::init_attrer7_utils__PrimingSecondOrderODEIntegrator() ;
}

size_t io_src_sizeof_er7_utils__PrimingSecondOrderODEIntegrator() {
    return sizeof(er7_utils::PrimingSecondOrderODEIntegrator) ;
}

void io_src_destruct_er7_utils__PrimingSecondOrderODEIntegrator(void* address __attribute__((unused)), int num __attribute__((unused))) {
    using namespace er7_utils;
    er7_utils::PrimingSecondOrderODEIntegrator* temp = (er7_utils::PrimingSecondOrderODEIntegrator*)address;
    for (int ii = 0; ii < num; ++ii) {
        temp[ii].~PrimingSecondOrderODEIntegrator();
    }
}

void io_src_delete_er7_utils__PrimingSecondOrderODEIntegrator(void* address) {
    delete (er7_utils::PrimingSecondOrderODEIntegrator*)address;
}

} //extern "C"

struct UnitsMaper7_utils__PrimingSecondOrderODEIntegrator {
    UnitsMaper7_utils__PrimingSecondOrderODEIntegrator() {
        Trick::UnitsMap* units_map_ptr = Trick::UnitsMap::units_map();
        units_map_ptr->add_param("PrimingSecondOrderODEIntegrator_state_size", "1") ;
        units_map_ptr->add_param("PrimingSecondOrderODEIntegrator_problem_type", "1") ;
        units_map_ptr->add_param("PrimingSecondOrderODEIntegrator_controls", "1") ;
        units_map_ptr->add_param("PrimingSecondOrderODEIntegrator_primer", "1") ;
        units_map_ptr->add_param("PrimingSecondOrderODEIntegrator_priming_state_size", "1") ;
        units_map_ptr->add_param("PrimingSecondOrderODEIntegrator_prime_counter", "1") ;
        units_map_ptr->add_param("PrimingSecondOrderODEIntegrator_primed", "1") ;
    }
} umer7_utils__PrimingSecondOrderODEIntegrator;

