/**
 * This file was automatically generated by the ICG based on the file:
 * /users/agirish/trick_tutorial/trick/trick_source/er7_utils/math/include/uint128.hh
 * This file contains database parameter declarations specific to the
 * data structures and enumerated types declared in the above file.
 * These database parameters are used by the Trick input and
 * data recording processors to gain access to important simulation
 * variable information.
 */

#define TRICK_IN_IOSRC
#include <stdlib.h>
#include "trick/MemoryManager.hh"
#include "trick/attributes.h"
#include "trick/parameter_types.h"
#include "trick/ClassSizeCheck.hh"
#include "trick/UnitsMap.hh"
#include "trick/checkpoint_stl.hh"
#include "/users/agirish/trick_tutorial/trick/trick_source/er7_utils/math/include/uint128.hh"

extern "C" {

ATTRIBUTES attrer7_utils__UInt128[] = {
{"low", "unsigned long", "1", "", "",
  "",
  15,TRICK_UNSIGNED_LONG, sizeof(unsigned long), 0, 0, Language_CPP, 4,
  0, NULL, 0, {{0, 0}, {0, 0}, {0, 0}, {0, 0}, {0, 0}, {0, 0}, {0, 0}, {0, 0}},
  NULL, NULL, NULL, NULL},
{"high", "unsigned long", "1", "", "",
  "",
  15,TRICK_UNSIGNED_LONG, sizeof(unsigned long), 0, 0, Language_CPP, 4,
  8, NULL, 0, {{0, 0}, {0, 0}, {0, 0}, {0, 0}, {0, 0}, {0, 0}, {0, 0}, {0, 0}},
  NULL, NULL, NULL, NULL},
{"", "", "1", "", "",
  "",
  15,TRICK_VOID, 0, 0, 0, Language_CPP, 0,
  0, NULL, 0, {{0, 0}, {0, 0}, {0, 0}, {0, 0}, {0, 0}, {0, 0}, {0, 0}, {0, 0}},
  NULL, NULL, NULL, NULL} };

} //extern "C"

namespace er7_utils {

void init_attrer7_utils__UInt128() {

    static int initialized ;
    if (initialized) {
        return;
    }
    initialized = 1;

}
}

extern "C" {

void init_attrer7_utils__UInt128_c_intf() {
    er7_utils::init_attrer7_utils__UInt128() ;
}

size_t io_src_sizeof_er7_utils__UInt128() {
    return sizeof(er7_utils::UInt128) ;
}

void* io_src_allocate_er7_utils__UInt128(int num) {
    er7_utils::UInt128* temp = (er7_utils::UInt128*)calloc(num, sizeof(er7_utils::UInt128));
    for (int ii = 0; ii < num; ++ii) {
        new(&temp[ii]) er7_utils::UInt128();
    }
    return (void*)temp;
}

void io_src_destruct_er7_utils__UInt128(void* address __attribute__((unused)), int num __attribute__((unused))) {
    using namespace er7_utils;
    er7_utils::UInt128* temp = (er7_utils::UInt128*)address;
    for (int ii = 0; ii < num; ++ii) {
        temp[ii].~UInt128();
    }
}

void io_src_delete_er7_utils__UInt128(void* address) {
    delete (er7_utils::UInt128*)address;
}

} //extern "C"

struct UnitsMaper7_utils__UInt128 {
    UnitsMaper7_utils__UInt128() {
        Trick::UnitsMap* units_map_ptr = Trick::UnitsMap::units_map();
        units_map_ptr->add_param("UInt128_low", "1") ;
        units_map_ptr->add_param("UInt128_high", "1") ;
    }
} umer7_utils__UInt128;

