/**
 * This file was automatically generated by the ICG based on the file:
 * /users/agirish/trick_tutorial/trick/trick_source/er7_utils/integration/mm4/include/mm4_second_order_ode_integrator.hh
 * This file contains database parameter declarations specific to the
 * data structures and enumerated types declared in the above file.
 * These database parameters are used by the Trick input and
 * data recording processors to gain access to important simulation
 * variable information.
 */

#define TRICK_IN_IOSRC
#include <stdlib.h>
#include "trick/MemoryManager.hh"
#include "trick/attributes.h"
#include "trick/parameter_types.h"
#include "trick/ClassSizeCheck.hh"
#include "trick/UnitsMap.hh"
#include "trick/checkpoint_stl.hh"
#include "/users/agirish/trick_tutorial/trick/trick_source/er7_utils/integration/mm4/include/mm4_second_order_ode_integrator.hh"

extern "C" {

ATTRIBUTES attrer7_utils__MM4SecondOrderODEIntegrator[] = {
{"state_size", "int", "1", "", "",
  "n The sizes of the generalized position and generalized velocity vectors.",
  15,TRICK_INTEGER, sizeof(int), 0, 0, Language_CPP, 4,
  40, NULL, 1, {{2, 0}, {0, 0}, {0, 0}, {0, 0}, {0, 0}, {0, 0}, {0, 0}, {0, 0}},
  NULL, NULL, NULL, NULL},
{"problem_type", "er7_utils::Integration::ODEProblemType", "1", "", "",
  "n The type of problem to be solved.",
  15,TRICK_ENUMERATED, 0, 0, 0, Language_CPP, 4,
  48, NULL, 0, {{0, 0}, {0, 0}, {0, 0}, {0, 0}, {0, 0}, {0, 0}, {0, 0}, {0, 0}},
  NULL, NULL, NULL, NULL},
{"pos_hist", "double", "1", "", "",
  "n Position history, initial plus results from first two steps.",
  15,TRICK_DOUBLE, sizeof(double), 0, 0, Language_CPP, 4,
  56, NULL, 2, {{3, 0}, {0, 0}, {0, 0}, {0, 0}, {0, 0}, {0, 0}, {0, 0}, {0, 0}},
  NULL, NULL, NULL, NULL},
{"vel_hist", "double", "1", "", "",
  "n Position history, initial plus results from first two steps.",
  15,TRICK_DOUBLE, sizeof(double), 0, 0, Language_CPP, 4,
  80, NULL, 2, {{3, 0}, {0, 0}, {0, 0}, {0, 0}, {0, 0}, {0, 0}, {0, 0}, {0, 0}},
  NULL, NULL, NULL, NULL},
{"posdot", "double", "1", "", "",
  "n Derivative of generalized position.",
  15,TRICK_DOUBLE, sizeof(double), 0, 0, Language_CPP, 4,
  104, NULL, 1, {{0, 0}, {0, 0}, {0, 0}, {0, 0}, {0, 0}, {0, 0}, {0, 0}, {0, 0}},
  NULL, NULL, NULL, NULL},
{"", "", "1", "", "",
  "",
  15,TRICK_VOID, 0, 0, 0, Language_CPP, 0,
  0, NULL, 0, {{0, 0}, {0, 0}, {0, 0}, {0, 0}, {0, 0}, {0, 0}, {0, 0}, {0, 0}},
  NULL, NULL, NULL, NULL} };

} //extern "C"

namespace er7_utils {

void init_attrer7_utils__MM4SecondOrderODEIntegrator() {

    static int initialized ;
    if (initialized) {
        return;
    }
    initialized = 1;

    trick_MM->add_attr_info(std::string(attrer7_utils__MM4SecondOrderODEIntegrator[1].type_name) , &attrer7_utils__MM4SecondOrderODEIntegrator[1], __FILE__ , __LINE__ ) ;

    ATTRIBUTES temp_attr ;

    trick_MM->add_attr_info( std::string("er7_utils::SecondOrderODEIntegrator"), &temp_attr , __FILE__ , __LINE__ ) ;
    trick_MM->add_attr_info( std::string("er7_utils::Er7UtilsDeletable"), &temp_attr , __FILE__ , __LINE__ ) ;
}
}

extern "C" {

void init_attrer7_utils__MM4SecondOrderODEIntegrator_c_intf() {
    er7_utils::init_attrer7_utils__MM4SecondOrderODEIntegrator() ;
}

size_t io_src_sizeof_er7_utils__MM4SecondOrderODEIntegrator() {
    return sizeof(er7_utils::MM4SecondOrderODEIntegrator) ;
}

void io_src_destruct_er7_utils__MM4SecondOrderODEIntegrator(void* address __attribute__((unused)), int num __attribute__((unused))) {
    using namespace er7_utils;
    er7_utils::MM4SecondOrderODEIntegrator* temp = (er7_utils::MM4SecondOrderODEIntegrator*)address;
    for (int ii = 0; ii < num; ++ii) {
        temp[ii].~MM4SecondOrderODEIntegrator();
    }
}

void io_src_delete_er7_utils__MM4SecondOrderODEIntegrator(void* address) {
    delete (er7_utils::MM4SecondOrderODEIntegrator*)address;
}

} //extern "C"

struct UnitsMaper7_utils__MM4SecondOrderODEIntegrator {
    UnitsMaper7_utils__MM4SecondOrderODEIntegrator() {
        Trick::UnitsMap* units_map_ptr = Trick::UnitsMap::units_map();
        units_map_ptr->add_param("MM4SecondOrderODEIntegrator_state_size", "1") ;
        units_map_ptr->add_param("MM4SecondOrderODEIntegrator_problem_type", "1") ;
        units_map_ptr->add_param("MM4SecondOrderODEIntegrator_pos_hist", "1") ;
        units_map_ptr->add_param("MM4SecondOrderODEIntegrator_vel_hist", "1") ;
        units_map_ptr->add_param("MM4SecondOrderODEIntegrator_posdot", "1") ;
    }
} umer7_utils__MM4SecondOrderODEIntegrator;

extern "C" {

ATTRIBUTES attrer7_utils__MM4SimpleSecondOrderODEIntegrator[] = {
{"state_size", "int", "1", "", "",
  "n The sizes of the generalized position and generalized velocity vectors.",
  15,TRICK_INTEGER, sizeof(int), 0, 0, Language_CPP, 4,
  40, NULL, 1, {{2, 0}, {0, 0}, {0, 0}, {0, 0}, {0, 0}, {0, 0}, {0, 0}, {0, 0}},
  NULL, NULL, NULL, NULL},
{"problem_type", "er7_utils::Integration::ODEProblemType", "1", "", "",
  "n The type of problem to be solved.",
  15,TRICK_ENUMERATED, 0, 0, 0, Language_CPP, 4,
  48, NULL, 0, {{0, 0}, {0, 0}, {0, 0}, {0, 0}, {0, 0}, {0, 0}, {0, 0}, {0, 0}},
  NULL, NULL, NULL, NULL},
{"pos_hist", "double", "1", "", "",
  "n Position history, initial plus results from first two steps.",
  15,TRICK_DOUBLE, sizeof(double), 0, 0, Language_CPP, 4,
  56, NULL, 2, {{3, 0}, {0, 0}, {0, 0}, {0, 0}, {0, 0}, {0, 0}, {0, 0}, {0, 0}},
  NULL, NULL, NULL, NULL},
{"vel_hist", "double", "1", "", "",
  "n Position history, initial plus results from first two steps.",
  15,TRICK_DOUBLE, sizeof(double), 0, 0, Language_CPP, 4,
  80, NULL, 2, {{3, 0}, {0, 0}, {0, 0}, {0, 0}, {0, 0}, {0, 0}, {0, 0}, {0, 0}},
  NULL, NULL, NULL, NULL},
{"posdot", "double", "1", "", "",
  "n Derivative of generalized position.",
  15,TRICK_DOUBLE, sizeof(double), 0, 0, Language_CPP, 4,
  104, NULL, 1, {{0, 0}, {0, 0}, {0, 0}, {0, 0}, {0, 0}, {0, 0}, {0, 0}, {0, 0}},
  NULL, NULL, NULL, NULL},
{"", "", "1", "", "",
  "",
  15,TRICK_VOID, 0, 0, 0, Language_CPP, 0,
  0, NULL, 0, {{0, 0}, {0, 0}, {0, 0}, {0, 0}, {0, 0}, {0, 0}, {0, 0}, {0, 0}},
  NULL, NULL, NULL, NULL} };

} //extern "C"

namespace er7_utils {

void init_attrer7_utils__MM4SimpleSecondOrderODEIntegrator() {

    static int initialized ;
    if (initialized) {
        return;
    }
    initialized = 1;

    trick_MM->add_attr_info(std::string(attrer7_utils__MM4SimpleSecondOrderODEIntegrator[1].type_name) , &attrer7_utils__MM4SimpleSecondOrderODEIntegrator[1], __FILE__ , __LINE__ ) ;

    ATTRIBUTES temp_attr ;

    trick_MM->add_attr_info( std::string("er7_utils::MM4SecondOrderODEIntegrator"), &temp_attr , __FILE__ , __LINE__ ) ;
    trick_MM->add_attr_info( std::string("er7_utils::Er7UtilsDeletable"), &temp_attr , __FILE__ , __LINE__ ) ;
}
}

extern "C" {

void init_attrer7_utils__MM4SimpleSecondOrderODEIntegrator_c_intf() {
    er7_utils::init_attrer7_utils__MM4SimpleSecondOrderODEIntegrator() ;
}

size_t io_src_sizeof_er7_utils__MM4SimpleSecondOrderODEIntegrator() {
    return sizeof(er7_utils::MM4SimpleSecondOrderODEIntegrator) ;
}

void* io_src_allocate_er7_utils__MM4SimpleSecondOrderODEIntegrator(int num) {
    er7_utils::MM4SimpleSecondOrderODEIntegrator* temp = (er7_utils::MM4SimpleSecondOrderODEIntegrator*)calloc(num, sizeof(er7_utils::MM4SimpleSecondOrderODEIntegrator));
    for (int ii = 0; ii < num; ++ii) {
        new(&temp[ii]) er7_utils::MM4SimpleSecondOrderODEIntegrator();
    }
    return (void*)temp;
}

void io_src_destruct_er7_utils__MM4SimpleSecondOrderODEIntegrator(void* address __attribute__((unused)), int num __attribute__((unused))) {
    using namespace er7_utils;
    er7_utils::MM4SimpleSecondOrderODEIntegrator* temp = (er7_utils::MM4SimpleSecondOrderODEIntegrator*)address;
    for (int ii = 0; ii < num; ++ii) {
        temp[ii].~MM4SimpleSecondOrderODEIntegrator();
    }
}

void io_src_delete_er7_utils__MM4SimpleSecondOrderODEIntegrator(void* address) {
    delete (er7_utils::MM4SimpleSecondOrderODEIntegrator*)address;
}

} //extern "C"

struct UnitsMaper7_utils__MM4SimpleSecondOrderODEIntegrator {
    UnitsMaper7_utils__MM4SimpleSecondOrderODEIntegrator() {
        Trick::UnitsMap* units_map_ptr = Trick::UnitsMap::units_map();
        units_map_ptr->add_param("MM4SimpleSecondOrderODEIntegrator_state_size", "1") ;
        units_map_ptr->add_param("MM4SimpleSecondOrderODEIntegrator_problem_type", "1") ;
        units_map_ptr->add_param("MM4SimpleSecondOrderODEIntegrator_pos_hist", "1") ;
        units_map_ptr->add_param("MM4SimpleSecondOrderODEIntegrator_vel_hist", "1") ;
        units_map_ptr->add_param("MM4SimpleSecondOrderODEIntegrator_posdot", "1") ;
    }
} umer7_utils__MM4SimpleSecondOrderODEIntegrator;

extern "C" {

ATTRIBUTES attrer7_utils__MM4GeneralizedDerivSecondOrderODEIntegrator[] = {
{"state_size", "int", "1", "", "",
  "n The sizes of the generalized position and generalized velocity vectors.",
  15,TRICK_INTEGER, sizeof(int), 0, 0, Language_CPP, 4,
  40, NULL, 1, {{2, 0}, {0, 0}, {0, 0}, {0, 0}, {0, 0}, {0, 0}, {0, 0}, {0, 0}},
  NULL, NULL, NULL, NULL},
{"problem_type", "er7_utils::Integration::ODEProblemType", "1", "", "",
  "n The type of problem to be solved.",
  15,TRICK_ENUMERATED, 0, 0, 0, Language_CPP, 4,
  48, NULL, 0, {{0, 0}, {0, 0}, {0, 0}, {0, 0}, {0, 0}, {0, 0}, {0, 0}, {0, 0}},
  NULL, NULL, NULL, NULL},
{"pos_hist", "double", "1", "", "",
  "n Position history, initial plus results from first two steps.",
  15,TRICK_DOUBLE, sizeof(double), 0, 0, Language_CPP, 4,
  56, NULL, 2, {{3, 0}, {0, 0}, {0, 0}, {0, 0}, {0, 0}, {0, 0}, {0, 0}, {0, 0}},
  NULL, NULL, NULL, NULL},
{"vel_hist", "double", "1", "", "",
  "n Position history, initial plus results from first two steps.",
  15,TRICK_DOUBLE, sizeof(double), 0, 0, Language_CPP, 4,
  80, NULL, 2, {{3, 0}, {0, 0}, {0, 0}, {0, 0}, {0, 0}, {0, 0}, {0, 0}, {0, 0}},
  NULL, NULL, NULL, NULL},
{"posdot", "double", "1", "", "",
  "n Derivative of generalized position.",
  15,TRICK_DOUBLE, sizeof(double), 0, 0, Language_CPP, 4,
  104, NULL, 1, {{0, 0}, {0, 0}, {0, 0}, {0, 0}, {0, 0}, {0, 0}, {0, 0}, {0, 0}},
  NULL, NULL, NULL, NULL},
{"", "", "1", "", "",
  "",
  15,TRICK_VOID, 0, 0, 0, Language_CPP, 0,
  0, NULL, 0, {{0, 0}, {0, 0}, {0, 0}, {0, 0}, {0, 0}, {0, 0}, {0, 0}, {0, 0}},
  NULL, NULL, NULL, NULL} };

} //extern "C"

namespace er7_utils {

void init_attrer7_utils__MM4GeneralizedDerivSecondOrderODEIntegrator() {

    static int initialized ;
    if (initialized) {
        return;
    }
    initialized = 1;

    trick_MM->add_attr_info(std::string(attrer7_utils__MM4GeneralizedDerivSecondOrderODEIntegrator[1].type_name) , &attrer7_utils__MM4GeneralizedDerivSecondOrderODEIntegrator[1], __FILE__ , __LINE__ ) ;

    ATTRIBUTES temp_attr ;

    trick_MM->add_attr_info( std::string("er7_utils::MM4SecondOrderODEIntegrator"), &temp_attr , __FILE__ , __LINE__ ) ;
    trick_MM->add_attr_info( std::string("er7_utils::Er7UtilsDeletable"), &temp_attr , __FILE__ , __LINE__ ) ;
}
}

extern "C" {

void init_attrer7_utils__MM4GeneralizedDerivSecondOrderODEIntegrator_c_intf() {
    er7_utils::init_attrer7_utils__MM4GeneralizedDerivSecondOrderODEIntegrator() ;
}

size_t io_src_sizeof_er7_utils__MM4GeneralizedDerivSecondOrderODEIntegrator() {
    return sizeof(er7_utils::MM4GeneralizedDerivSecondOrderODEIntegrator) ;
}

void* io_src_allocate_er7_utils__MM4GeneralizedDerivSecondOrderODEIntegrator(int num) {
    er7_utils::MM4GeneralizedDerivSecondOrderODEIntegrator* temp = (er7_utils::MM4GeneralizedDerivSecondOrderODEIntegrator*)calloc(num, sizeof(er7_utils::MM4GeneralizedDerivSecondOrderODEIntegrator));
    for (int ii = 0; ii < num; ++ii) {
        new(&temp[ii]) er7_utils::MM4GeneralizedDerivSecondOrderODEIntegrator();
    }
    return (void*)temp;
}

void io_src_destruct_er7_utils__MM4GeneralizedDerivSecondOrderODEIntegrator(void* address __attribute__((unused)), int num __attribute__((unused))) {
    using namespace er7_utils;
    er7_utils::MM4GeneralizedDerivSecondOrderODEIntegrator* temp = (er7_utils::MM4GeneralizedDerivSecondOrderODEIntegrator*)address;
    for (int ii = 0; ii < num; ++ii) {
        temp[ii].~MM4GeneralizedDerivSecondOrderODEIntegrator();
    }
}

void io_src_delete_er7_utils__MM4GeneralizedDerivSecondOrderODEIntegrator(void* address) {
    delete (er7_utils::MM4GeneralizedDerivSecondOrderODEIntegrator*)address;
}

} //extern "C"

struct UnitsMaper7_utils__MM4GeneralizedDerivSecondOrderODEIntegrator {
    UnitsMaper7_utils__MM4GeneralizedDerivSecondOrderODEIntegrator() {
        Trick::UnitsMap* units_map_ptr = Trick::UnitsMap::units_map();
        units_map_ptr->add_param("MM4GeneralizedDerivSecondOrderODEIntegrator_state_size", "1") ;
        units_map_ptr->add_param("MM4GeneralizedDerivSecondOrderODEIntegrator_problem_type", "1") ;
        units_map_ptr->add_param("MM4GeneralizedDerivSecondOrderODEIntegrator_pos_hist", "1") ;
        units_map_ptr->add_param("MM4GeneralizedDerivSecondOrderODEIntegrator_vel_hist", "1") ;
        units_map_ptr->add_param("MM4GeneralizedDerivSecondOrderODEIntegrator_posdot", "1") ;
    }
} umer7_utils__MM4GeneralizedDerivSecondOrderODEIntegrator;

